PitTestRoutine
Team3256/FRC_Programming_2024 pull request #115
Opened 2024-01-30 01:11 UTC by Smogless

2024-01-30 01:17 UTC, realjoshuau requested changes
just move file and ur good

2024-01-30 01:17 UTC, realjoshuau commented on src/main/java/frc/robot/commands/EndCurrentCommand.java
this might be scuffed

2024-01-30 01:17 UTC, realjoshuau commented on src/main/java/frc/robot/subsystems/swerve/commands/PitTestRoutine.java
file is fine just move it out of here

2024-01-30 01:19 UTC, Smogless commented on src/main/java/frc/robot/commands/EndCurrentCommand.java
thats what I like to hear

2024-01-31 05:33 UTC, 3LucasZ reviewed
1. Unfortunately have to wait for climb + arm to be integrated, so will put in blocked
2. Need video of EndCurrentCommand working

Great job overall.

2024-01-31 05:33 UTC, 3LucasZ commented on src/main/java/frc/robot/commands/EndCurrentCommand.java
> +}
Please show a picture/video of this command working in sim

2024-02-03 02:16 UTC, realjoshuau requested changes
fix

2024-02-03 22:06 UTC, realjoshuau approved these changes
lgtm

2024-02-03 22:06 UTC, realjoshuau commented on src/main/java/frc/robot/subsystems/swerve/commands/TeleopSwerve.java
Why did you remove the executable bit on this file?

2024-02-03 22:07 UTC, merged