Robotviz
Team3256/FRC_Programming_2024 pull request #120
Opened 2024-01-31 05:17 UTC by 3LucasZ

2024-01-31 05:18 UTC, 3LucasZ commented
Sim vid
https://github.com/Team3256/FRC_Programming_2024/assets/72239682/2a9f5d88-aba8-47bc-81dd-73b58398880c

2024-01-31 05:45 UTC, realjoshuau requested changes
Generally good, but has syntax errors that will crash things. 

(Also is the intake supposed to spin like that in the video? I think it is but do not remember)

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/RobotContainer.java
> +    if (FeatureFlags.kRobotVizEnabled) {
I would want RobotViz to only enable if `RobotMode` is SIM or REPLAY.

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/RobotContainer.java
> +    robotViz.update(dt);
**`robotViz` WILL BE NULL IF `kRobotVizEnabled` IS FALSE!!** 

Add a check to the feature flags & robot mode here.

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/robotviz/RobotVizConstants.java
> +  // --Spoof--
What does this mean?

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/robotviz/RobotVizConstants.java
Why is this in its own file?

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/robotviz/RobotVizConstants.java
Actually, you're probably right to keep this in here, since it's not essential to the actual robot functionality (but still essential for us :p)

2024-01-31 05:45 UTC, realjoshuau commented on src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
> +  public void updatePose(Rotation2d gyroYaw, SwerveModulePosition[] swerveModulePositions) {
Good thinking

2024-01-31 05:52 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    if (FeatureFlags.kRobotVizEnabled) {
k ill have it only on sim, no

2024-01-31 05:53 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    robotViz.update(dt);
WHOOPS good catch.

2024-01-31 05:57 UTC, 3LucasZ commented on src/main/java/frc/robot/robotviz/RobotVizConstants.java
> +  // --Spoof--
Just made comment.

2024-01-31 05:58 UTC, 3LucasZ commented on src/main/java/frc/robot/robotviz/RobotVizConstants.java
Yeah

2024-01-31 06:10 UTC, 3LucasZ commented
The intake spins when I press "teleop mode" instantaneously without me running any intake command. This is definitely erroneous behavior. It's a bug with the intake, not with the visualizer. The viz job is only to display the angle that the intake believes it holds.

2024-01-31 06:16 UTC, realjoshuau approved these changes
LGTM. Nice job!

2024-01-31 06:16 UTC, realjoshuau commented
> The intake spins when I press "teleop mode" instantaneously without me running any intake command. This is definitely erroneous behavior. It's a bug with the intake, not with the visualizer. The viz job is only to display the angle that the intake believes it holds.

Hm. @DragonXDev you might need to fix this?

2024-02-01 23:14 UTC, 3LucasZ commented
Thank u. merging now.

2024-02-01 23:15 UTC, merged