AutoChooser and Runner
Team3256/FRC_Programming_2024 pull request #16
Opened 2024-01-09 00:45 UTC by ThatXliner

- Closes #9 

Untested. I'm not even sure if this code would work

2024-01-09 00:47 UTC, realjoshuau reviewed
Seems good to me!

2024-01-09 00:47 UTC, realjoshuau commented on src/main/java/frc/robot/autos/pathPlannerAuto.java
> +public class pathPlannerAuto extends SequentialCommandGroup {
you should change this to proper casing

2024-01-09 00:48 UTC, ThatXliner commented on src/main/java/frc/robot/autos/pathPlannerAuto.java
> +public class pathPlannerAuto extends SequentialCommandGroup {
The `exampleAuto` was like that

2024-01-12 06:36 UTC, ChaoticChaosTheGreat commented
Added spotless, accept my pr #19

2024-01-13 00:43 UTC, 3LucasZ commented
Please post a video of this working in sim, before I can review.

2024-01-13 00:44 UTC, 3LucasZ requested changes
So far so good, but please post a video of this working in simulation before I can further review.

2024-01-13 00:51 UTC, ThatXliner commented
Closed because the merge conflicts are crazy

2024-01-13 00:51 UTC, closed without merging