Azimuth.exe
Team3256/FRC_Programming_2024 pull request #191
Opened 2024-03-08 00:43 UTC by memori034

need pid fixes

2024-03-08 04:31 UTC, realjoshuau requested changes
do you need the azimuth direction to switch in between matches? you can get it from the DriverStation class

2024-03-08 04:34 UTC, realjoshuau commented
ALSO LINT YO STUFF

2024-03-11 05:39 UTC, memori034 commented
> do you need the azimuth direction to switch in between matches? you can get it from the DriverStation class

ok it now changes with ds alliance

2024-03-11 05:39 UTC, memori034 commented
> ALSO LINT YO STUFF

gradle skill issues im not tryna fix

2024-03-11 05:40 UTC, memori034 commented
we test after avr

2024-03-19 05:27 UTC, memori034 commented on src/main/java/frc/robot/RobotContainer.java
> +    if (isRed = true) { // RED
meow:3

2024-03-19 05:27 UTC, memori034 commented on src/main/java/frc/robot/RobotContainer.java
> +    if (isRed = true) { // RED
i fix

2024-03-20 17:35 UTC, merged