Task slow mode swerve foc
Team3256/FRC_Programming_2024 pull request #35
Opened 2024-01-13 01:19 UTC by Smogless

added teleopswervelimited and enable FOC
AKit issues -> simulateJava doesnt work

2024-01-13 01:42 UTC, ChaoticChaosTheGreat commented
Use last year code for fix : https://github.com/Team3256/FRC_Programming_2023/blob/main/src/main/java/frc/robot/Robot.java

2024-01-14 02:58 UTC, ChaoticChaosTheGreat commented
someone merge this already

2024-01-14 02:59 UTC, 3LucasZ commented
@ChaoticChaosTheGreat, please give us time to review your PR. In the meantime, please post a design document and a video of this working in simulation AND in real life. We can not merge this PR until that is done. Thank you for understanding.

2024-01-14 03:05 UTC, 3LucasZ requested changes

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/deploy/pathplanner/paths/Red2-1Speaker-Mobility-L.path
> +      "prevControl": {
Why is a path included here? Please remove, this is unrelated to the issue being solved.

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/deploy/pathplanner/navgrid.json
> +{"field_size":{"x":16.54,"y":8.21},"nodeSizeMeters":0.3,"grid":[[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true
Unrelated to the issue

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +      public static final double kSlowModeRatio = 0.4;
make this kSlowModeSpeed instead of a ratio.

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +      public static final double kSlowModeRatio = 0.4;
I mean, kMaxSlowVelocity

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +      public static final double kMaxAngularVelocity = 5;
make a kMaxAngularSlowVelocity

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +      public static final double kMaxAngularVelocity = 5;
in addition to what is above

2024-01-14 03:05 UTC, 3LucasZ commented on src/main/java/frc/robot/commands/TeleopSwerveLimited.java
> +    swerveDrive.drive(translation, rAxis, robotCentricSup.getAsBoolean(), kOpenLoop);
won't review this section until it works IRL and in simulation, and there is a design doc linked to this PR (written in Google Docs or Notion)

2024-01-14 03:36 UTC, ChaoticChaosTheGreat commented
> @ChaoticChaosTheGreat, please give us time to review your PR. In the meantime, please post a design document and a video of this working in simulation AND in real life. We can not merge this PR until that is done. Thank you for understanding.

not my pr, this has just been open for too long

2024-01-14 04:35 UTC, ChaoticChaosTheGreat commented
Also simulation of swerve does not work as of right now, will test on Monday if we have time. @Smogless

2024-01-16 00:21 UTC, 3LucasZ approved these changes
Looks good, works.

2024-01-16 00:23 UTC, merged