Auto align - INCOMPLETE: need to fill out position constants
Team3256/FRC_Programming_2024 pull request #44
Opened 2024-01-13 22:11 UTC by ChaoticChaosTheGreat

yo

2024-01-14 04:10 UTC, ChaoticChaosTheGreat commented
Design Doc: https://www.notion.so/warriorborgs/Auto-Align-b19ec3943dfa43a5b86a708d382986c5

2024-01-14 05:13 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> +  public static final boolean kAlliance = false; // true = blue, false = red
Need to add some sort of interface to change this value in shuffleboard.

2024-01-15 19:58 UTC, warriorborgs approved these changes

2024-01-15 19:59 UTC, realjoshuau submitted a review, later dismissed

2024-01-15 22:38 UTC, 3LucasZ commented
Get this working in sim and send an image/video, please.

2024-01-16 09:22 UTC, 3LucasZ requested changes

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/deploy/pathplanner/paths/New Path.path
> +    {
why make a new path?

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +  public static final boolean kAlliance = false; // true = blue, false = red
you can change the value during sim. Look at the alliance color, and check blue/red in the GUI. This constant is a terrible way of assigning this value. II can help you with this on Friday if you remind me.

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +  private final Joystick joystick = new Joystick(1);
Please, do not use Joystick. Please, use CommandXboxController (drive or operator, or make new one called tester if you really need). Please, do not use Joystick.

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/PathPlannerAuto.java
> +// https://github.com/Team3256
Make a comment explaining what this file does. Also, looks very repetitive (something we have implemented before). Is this just Auto Chooser and Runner?

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/PathGeneration.java
> +// Use of this source code is governed by a
empty class? remove if this is just a placeholder?

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoAmp.java
> +// Copyright (c) 2024 FRC 3256
rename file to something better please

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoAmp.java
> +        new PathConstraints(3.0, 4.0, Units.degreesToRadians(540), Units.degreesToRadians(720));
make these constants. the first rule is to not use numbers out in the open like this. make descriptive constants, please.

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoAmp.java
> +        AutoBuilder.pathfindToPose(scoringLocation, constraints, 0.0, 0.0);
tell us what 0.0 and 0.0 means through a constant in the constant file, please

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoAmp.java
> +    super.initialize();
why calling initialize in the bottom?

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoSpeaker.java
> +// https://github.com/Team3256
need better filename

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoSpeaker.java
> +    if (kAlliance == false) {
please, use Robot.getAlliance feature instead of this. I can help you with this on friday if you ask me

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoSpeaker.java
> +        new PathConstraints(3.0, 4.0, Units.degreesToRadians(540), Units.degreesToRadians(720));
please, do not use numbers out in the open like this and use constants

2024-01-16 09:22 UTC, 3LucasZ commented on src/main/java/frc/robot/autos/pathgeneration/helpers/ParentCommand.java
> +    }
May not be necessary, will take a look again after you make requested changes.

2024-01-16 20:07 UTC, ChaoticChaosTheGreat commented on src/main/deploy/pathplanner/paths/New Path.path
> +    {
Sorry, it was used to get the waypoints for dpg, will delete.

2024-01-16 20:08 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +  private final Joystick joystick = new Joystick(1);
Ye again sorry, I didn't know how to get the auto-align command to run in sim so I was trying some new things.

2024-01-16 20:08 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/autos/PathPlannerAuto.java
> +// https://github.com/Team3256
This file needs to be deleted.

2024-01-16 23:46 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/autos/pathgeneration/commands/AutoAmp.java
> +    super.initialize();
Running the parentcommand initialize to add the child commands.

2024-01-17 00:38 UTC, ChaoticChaosTheGreat commented
Removed ParentCommand (unnecessary ), made all numbers constants with AutoConstants class, fixed bug in sim which didn't let you run the command twice, removed alliance constant and replaced with retrieving the alliance from he DS.

2024-01-17 05:32 UTC, 3LucasZ commented
great job.

2024-01-17 06:56 UTC, 3LucasZ approved these changes
Very good job, @ChaoticChaosTheGreat (Ryan).

2024-01-17 06:57 UTC, 3LucasZ commented
You have the honors to merge when you are ready.

2024-01-17 15:54 UTC, merged

2024-01-17 15:54 UTC, ChaoticChaosTheGreat commented
> Very good job, @ChaoticChaosTheGreat (Ryan).

Thanks!!! 😊