added second motor PID
Team3256/FRC_Programming_2024 pull request #48
Opened 2024-01-13 22:59 UTC by ChaoticChaosTheGreat

2024-01-13 23:00 UTC, ChaoticChaosTheGreat commented
DO NOT MERGE TO MAIN. JUST FOR REVIEW

2024-01-14 03:08 UTC, 3LucasZ requested changes

2024-01-14 03:08 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static double kFeederRPM2 = 700;
Be more descriptive. What is difference between RPM and RPM2? At least, provide a description.

2024-01-14 03:08 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.a().onTrue(new SetFeederRPM(shooter, Constants.ShooterConstants.kFeederRPM / 60));
why are you dividing by 60? provide explanation, and make it into a constant. Include why in your design doc

2024-01-14 03:41 UTC, realjoshuau commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.a().onTrue(new SetFeederRPM(shooter, Constants.ShooterConstants.kFeederRPM / 60));
This was explained in the comment.

2024-01-14 03:41 UTC, realjoshuau commented on src/main/java/frc/robot/Constants.java
> +    public static double kFeederRPM2 = 700;
RPM2 was left for testing.

2024-01-14 04:11 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> +    public static double kFeederRPM2 = 700;
In original issue, it said to create a command that could run to two different RPMS this was the solution.

2024-01-14 04:13 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> +    public static double kFeederRPM2 = 700;
Pretty self-explanatory: just a second RPM that can be used. As of right now it serves no purpose because we haven't tuned any values which is why it doesn't have a specific name.

2024-01-14 04:13 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.a().onTrue(new SetFeederRPM(shooter, Constants.ShooterConstants.kFeederRPM / 60));
I don't think this deserves to be a constant because it is just a unit conversion.

2024-01-20 03:23 UTC, realjoshuau commented
Closing since git is not liking the rename.

2024-01-20 03:23 UTC, realjoshuau commented
Sorry!

2024-01-20 04:14 UTC, ChaoticChaosTheGreat commented
Just revert the commits, I know how to rename if you revert back.

2024-01-20 08:59 UTC, closed without merging