Implemented speaker and amp commands within shooter.
Team3256/FRC_Programming_2024 pull request #55
Opened 2024-01-14 04:49 UTC by ChaoticChaosTheGreat

Added a score speaker and amp command within shooter subsystem. Values will need to be tuned.

2024-01-14 04:52 UTC, ChaoticChaosTheGreat commented
https://docs.google.com/document/d/1dCsHbJzHSj-CACLkWGzveg6ksg9Xp-R9MHBP6ya1c3g/edit#heading=h.3al4l9f2uc1e

2024-01-16 09:25 UTC, 3LucasZ requested changes

2024-01-16 09:25 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static double AmpRPM = 1000; // TODO: Tune value
I believe we will use RPS from now on instead of RPM. but we can discuss, if RPM is better.

2024-01-16 09:25 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreAmp.java
> +  }
if isFinished returns false, when will the command ever finish?

2024-01-16 09:25 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreSpeaker.java
> +  @Override
if isFinished always false, when will command finish?

2024-01-16 09:25 UTC, 3LucasZ commented
Needs a better PR name before further review.

2024-01-16 19:38 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> +    public static double AmpRPM = 1000; // TODO: Tune value
It's not which is better the function takes in RPS.  But RPM is easier to think about.

2024-01-16 19:41 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreSpeaker.java
> +  @Override
Same explanation as AMP.

2024-01-16 19:42 UTC, ChaoticChaosTheGreat commented
> Needs a better PR name before further review.

What's a better PR name, this describes exactly what it implements. @3LucasZ

2024-01-17 05:29 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static double AmpRPM = 1000; // TODO: Tune value
Why is RPM easier to think about than RPS? Will that be the new standard from now on?

2024-01-17 05:30 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreAmp.java
> +  }
There should be one overarching command that does all of that together: rev up shooter, feed into shooter, turn them off. It can be sequential/parallel/etc composing/reusing other commands.

2024-01-17 05:31 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreSpeaker.java
> +  @Override
Same reply as AMP.

2024-01-17 06:07 UTC, ChaoticChaosTheGreat commented
Alright thanks.

2024-01-17 06:10 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreAmp.java
> +  }
Agreed, but this is just a draft pr and the intake subsystem + arm subsystem haven't been approved yet so I cannot create commands within those classes. As for now this PR is just for the RPM constants that would shoot into this speaker/amp not necessarily the whole command.

2024-01-17 06:12 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> +    public static double AmpRPM = 1000; // TODO: Tune value
Most motor vendors give their motor max speeds and such as RPM. RPS is rarely used, and whenever the speed of rotations is described you usually think about it in RPM. Its not too big of a deal honestly, maybe just get a second opinion from @realjoshuau or something and then I can change it if necessary.

2024-01-17 06:59 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/ScoreAmp.java
> +  }
Good point.

2024-01-17 06:59 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static double AmpRPM = 1000; // TODO: Tune value
Good point, good job.

2024-01-17 07:00 UTC, 3LucasZ commented
Thanks to you, not to me, I didn't do anything :).

2024-01-17 07:01 UTC, 3LucasZ approved these changes
Looks good ;D. Great job, @ChaoticChaosTheGreat (Mr. Abraham).

2024-01-17 15:56 UTC, ChaoticChaosTheGreat commented
> Squash and merge, when you are ready. Thanks for taking back the rough criticism kindly.

Thanks for the approval! This branch unfortunately will not be merged until design can give us some kind of robot for us to test presets with. Thanks for the comments.

2024-01-30 01:28 UTC, closed without merging

2024-01-30 01:28 UTC, ChaoticChaosTheGreat commented
Completed in another branch