Intake subsystem
Team3256/FRC_Programming_2024 pull request #65
Opened 2024-01-15 22:44 UTC by DragonXDev

Implementation of basic Intake Subsystem with intake in / out commands.

- Closes #25

2024-01-15 23:04 UTC, 3LucasZ requested changes
Not all the changes, but some to give you a baseline. Still needs a lot of work. Looks like copy pasted code, and I'm not too happy about that, but make sure to clean up the unnecessary stuff.

2024-01-15 23:04 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public int kRightDistanceSensorID = 21;
we aren't using distance sensor

2024-01-15 23:04 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static final double kTriggerThresholdTimeCone = 0.5;
we aren't using cones

2024-01-15 23:04 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static final double kLatchCubeSpeed = -0.15;
we aren't using cones

2024-01-15 23:04 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/SetIntakeOff.java
> +// Copyright (c) 2024 FRC 3256
SetIntakeOff doesnt sound like IntakeIn and IntakeOut

2024-01-15 23:05 UTC, realjoshuau submitted a review, later dismissed
???

2024-01-15 23:05 UTC, realjoshuau commented on src/main/java/frc/robot/Constants.java
> +      public static boolean kIntakeEnabled;
this needs to be final

2024-01-15 23:57 UTC, ChaoticChaosTheGreat requested changes
LGTM, minor changes

2024-01-15 23:57 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeIn.java
> +  private final DigitalInput input = new DigitalInput(0);
Change port to a constant

2024-01-15 23:57 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeOut.java
> +  private final DigitalInput input = new DigitalInput(0);
also change port to constant

2024-01-16 00:10 UTC, ChaoticChaosTheGreat submitted a review, later dismissed
Looks Good! :DDDDDDDDDD

2024-01-16 09:14 UTC, 3LucasZ submitted a review, later dismissed
Sorry for the coarse comments and bad grammar. Lots of mistakes in this PR that must be fixed.

2024-01-16 09:14 UTC, 3LucasZ commented on gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
why changing grade?

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +      public static final boolean kSwerveEnabled = false;
keep true, please

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> -      public static final boolean kIntakeEnabled = false;
true

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static final boolean kBeamBreak = false;
not descriptive enough. kBeamBreak detected? kBeamBreak is being used? etc?

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    // optional
wdym optional?

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.y().onTrue(new IntakeIn(intake));
whileTrue is better, you want it to stop intaking once Sam releases his fingers

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.b().onTrue(new IntakeOut(intake));
whileTrue

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    // optional
j remove it for now

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.povUp().onTrue(new IntakeOff(intake));
remove this too

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeIn.java
> +  private final DigitalInput input = new DigitalInput(kIntakeBeamBreakPort);
bad name

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeIn.java
> +  private final DigitalInput input = new DigitalInput(kIntakeBeamBreakPort);
dont instantiate DigitalInputs in command, this should all be part of the subsystem

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeOff.java
> +  @Override
you only need initialize set to off, and isFinished set true. everything else is waffle.

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeOut.java
> +      input = new DigitalInput(kIntakeBeamBreakPort);
please, dont use beam break instead command. this should be part of the subsystem as a whole.

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/intake/commands/IntakeVoltage.java
> +
Check comments in IntakeOff, similar mistakes. just sent initialize and isFinished, please.

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/SetShooterOff.java
>    public boolean isFinished() {
dont change shooter in an intake branch...

2024-01-16 09:14 UTC, 3LucasZ commented on src/main/java/frc/robot/subsystems/shooter/commands/SetShooterVoltage.java
> -    return false;
dont change shooter please

2024-01-16 19:44 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    // optional
The comment was meant to signify that the bindings were temporary.

2024-01-16 19:45 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.y().onTrue(new IntakeIn(intake));
Actually no, you don't want him thinking about when to stop since has so many other things he has to think about. The function will stop when it has intaken a piece. This does need to be changed to ontrue though.

2024-01-16 19:46 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.b().onTrue(new IntakeOut(intake));
Same reason as above

2024-01-16 19:47 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    operator.povUp().onTrue(new IntakeOff(intake));
Was left for testing and also if we need to turn off the intake if the piece never enters the subsystem.

2024-01-16 20:52 UTC, DragonXDev commented on gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
Correction, gradle was not changed in any way as shown in the file, it was simply regenerated. It seemed to be that the gradle-wrapper properties were corrupted which is why they were regenerated, but they were not. There is no change.

2024-01-16 20:56 UTC, DragonXDev commented on src/main/java/frc/robot/Constants.java
> -      public static final boolean kIntakeEnabled = false;
Sorry, what is the issue here? This is showing that `public static final boolean kIntakeEnabled = false;` is removed, and above, the intake is enabled.

2024-01-16 20:58 UTC, DragonXDev commented on src/main/java/frc/robot/Constants.java
> +    public static final boolean kBeamBreak = false;
`kBeamBreak` is a boolean describing whether the beam break is enabled, not whether it has detected an object, I will update this instead with `kBeamBreakEnabled`.

2024-01-16 23:30 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/Constants.java
> -      public static final boolean kIntakeEnabled = false;
set arm enabled and intake enable to true.

2024-01-17 00:51 UTC, ChaoticChaosTheGreat submitted a review, later dismissed
Minor changes, test with real robot to make sure the beam-break detection actually works.

2024-01-17 00:58 UTC, DragonXDev commented on src/main/java/frc/robot/Constants.java
> +    public static final double kOuttakeNoteVoltage = -16;
@realjoshuau I believe he told me to use voltages, 8 volts for intake, and -16 for outtake.

2024-01-17 05:27 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> -      public static final boolean kIntakeEnabled = false;
_Sorry, misread, this is ok, good job, my bad_

2024-01-17 05:28 UTC, 3LucasZ commented on src/main/java/frc/robot/Constants.java
> +    public static final double kOuttakeNoteVoltage = -16;
K, well, whatever floats your guys boat. As long as the reasoning is explained in design doc, its ok.

2024-01-18 01:47 UTC, ChaoticChaosTheGreat commented
Added to SimViz file and implemented the SimulationPeriodic but for some reason the voltage is always zero even when running the IntakeIn Command

2024-01-18 02:16 UTC, ChaoticChaosTheGreat commented
Fixed the issue in sim, here is the picture of it working in sim (sorry I don't have any screen-recording software but you can try running it locally or just take my word). 

<img width="727" alt="Screenshot 2024-01-17 at 6 15 03 PM" src="https://github.com/Team3256/FRC_Programming_2024/assets/62819056/8396db15-f912-462c-a464-aa2b88e34440">

2024-01-18 06:54 UTC, DragonXDev commented
Here is the implementation of the code in a simulation. The simulation utilizes a DIOSim to model the BeamBreak, and RPM Constants for the speed of the intake and outtake, that need to be fine tuned. Also, @realjoshuau said we are going to be using PID for the motors, causing the motors to not instantly rotate and at the RPM constant.

Simulation Video:
https://drive.google.com/file/d/1US7jkH9V2MM73CmPkSXIUNX_cJ9s7lpj/view?usp=sharing

2024-01-18 06:56 UTC, realjoshuau commented
You guys are absolutely insane. Great work. 

I can't review it at the moment since I'm busy for today and partially tomorrow, but I will certainly try and review this before Friday.

2024-01-18 20:33 UTC, ChaoticChaosTheGreat commented on src/main/java/frc/robot/RobotContainer.java
> +    driver.a().onTrue(new Shoot(shooter, 10));
Just for clarification: the binding was changed because we ran out of operator controllers to bind with intake for testing.

2024-01-19 05:43 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotContainer.java
> +    driver.a().onTrue(new Shoot(shooter, 10));
(Completely optional) in that case, create a new controller called "tester" set to port #2. Then, you can bind whatever extra buttons on it for more buttons.

2024-01-19 23:23 UTC, 3LucasZ approved these changes
Wow, spectacular job guys! Ready to merge.

2024-01-19 23:24 UTC, 3LucasZ approved these changes

2024-01-19 23:25 UTC, merged