Feat/swerve
Team3256/FRC_Programming_2024 pull request #66
Opened 2024-01-15 23:40 UTC by memori034

2024-01-16 09:05 UTC, 3LucasZ requested changes
Looks to much like a copy paste. Please delete all unnecessary things (LockSwerveX, StatisticsHelper, etc) that are unrelated to the issue you are trying to solve.

2024-01-16 09:05 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotType.java
> +// Copyright (c) 2023 FRC 3256
We only have one robot type, this isn't necessary.

2024-01-16 09:05 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotType.java
> +}
please add back TeleopServe

2024-01-16 09:05 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotType.java
> +}
*command

2024-01-16 09:05 UTC, 3LucasZ commented on src/main/java/frc/robot/RobotType.java
> +}
unable to comment on the file itself since the file original was removed, so commenting here

2024-01-16 09:06 UTC, 3LucasZ commented
Needs a design doc and video of working in simulation before further review. Also made comments above.

2024-01-22 19:26 UTC, memori034 commented on src/main/java/frc/robot/RobotType.java
> +}
can you reexplain please

2024-02-03 02:17 UTC, realjoshuau commented
Merge azimuth & rate limits from this

2024-02-03 02:17 UTC, closed without merging