Arm Subsystem
Team3256/FRC_Programming_2024 pull request #79
Opened 2024-01-20 00:00 UTC by gxu0904

- arm subsystem
- commands to move the arm to ground position and shooter position.

2024-01-20 05:58 UTC, ChaoticChaosTheGreat commented
Wait is there a reason we used WPILIB's PIDController instead of the TalonFx one? Would be more standard + more accurate if we used the one from the phoenix 6 library. 
See motion profiling and position control here: https://pro.docs.ctr-electronics.com/en/latest/docs/api-reference/device-specific/talonfx/basic-pid-control.html#position-control

2024-01-20 08:56 UTC, realjoshuau commented
Arm subsystem has a separate absolute encoder that doesn't allow us to use TalonFX PID.

2024-01-20 08:57 UTC, realjoshuau commented
The TalonFX encoder is **not** absolute, so you can't reliably set positions on them.

2024-01-20 16:10 UTC, ChaoticChaosTheGreat commented
Ah I see. So no motion magic then?

2024-01-21 00:37 UTC, 3LucasZ commented
I think we will use PIDCommand instead of PIDSubsystem, since that's how we've been doing it

2024-01-21 00:38 UTC, 3LucasZ commented
There's only 2 angles (arm fully up and arm fully down), we can PID all the way up/down really fast and stop when the encoder doesn't notice signficant change.

2024-01-31 04:18 UTC, realjoshuau commented
Design has changed this subsystem **significantly**.  Look at this issue: #116, and submit another PR. You should base it off of this, since there are not many changes.

2024-01-31 04:19 UTC, realjoshuau commented
Design has changed this subsystem **significantly** since assembly refuses to add sensors. Look at this issue: #116, and submit another PR. You should base it off of this, since there are not many changes.

2024-02-03 01:31 UTC, 3LucasZ requested changes
Nice job! I have some small requests. Next step will be sim.

2024-02-03 01:31 UTC, 3LucasZ commented on vendordeps/REVLib-2024.json
> +{
What is this file for?

2024-02-04 03:06 UTC, realjoshuau approved these changes
whatever

2024-02-04 03:06 UTC, merged